# Generated by Django 4.2.13 on 2026-05-15 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=128, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'created_at'], name='tenders_pro_provide_9f9bfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_timestamp', models.DateTimeField(db_index=True)),
                ('total_hits', models.PositiveIntegerField(default=0)),
                ('success_hits', models.PositiveIntegerField(default=0)),
                ('failure_hits', models.PositiveIntegerField(default=0)),
                ('total_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_output_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_agg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hour_timestamp'],
                'unique_together': {('user', 'hour_timestamp')},
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('endpoint', models.CharField(default='/api/v1/tender-extractor/', max_length=256)),
                ('provider', models.CharField(blank=True, max_length=64, null=True)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=16)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='tenders_api_user_id_43baf5_idx'), models.Index(fields=['status'], name='tenders_api_status_983b63_idx')],
            },
        ),
    ]
